---
- name: Create borgmatic directory
  when: ansible_facts['os_family'] != 'Darwin'
  become: true
  ansible.builtin.file:
    group: root
    mode: "0750"
    owner: root
    path: /etc/borgmatic.d
    state: directory
- name: Copy borgmatic config
  when: ansible_facts['os_family'] != 'Darwin'
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/config.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Add borgmatic backup & prune job
  when: ansible_facts['os_family'] != 'Darwin'
  become: true
  ansible.builtin.cron:
    day: "*"
    hour: "*/6"
    job: /usr/local/bin/borgmatic -C -p
    minute: "15"
    month: "*"
    name: borgmatic create + prune
    user: root
    weekday: "*"
