---
- name: Reload systemd for mailrise
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: true
- name: Restart mailrise
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ enabled_services }}"
- name: Test notifications
  ansible.builtin.shell:
    cmd: 'sleep 5s;echo "Testing notifications on {{ inventory_hostname }}!" | msmtp root'
  become: true
  changed_when: true
