---
- name: Create config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/forgejo"
    state: directory
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: forgejo
    image: codeberg.org/forgejo/forgejo:{{ forgejo_version }}
    state: quadlet
    quadlet_filename: forgejo-container
    network: "{{ default_podman_interface }}"
    env:
      USE_UID: 1000
      USE_GID: 1000
    ports:
      - 127.0.0.1:{{ forgejo_port }}:3000
    volumes:
      - "{{ podman_data_dir }}/forgejo:/data:rw,z"
      - /etc/localtime:/etc/localtime:ro,z
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for forgejo
    - Restart forgejo
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/forgejo.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for forgejo
    - Restart forgejo
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/forgejo.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
