---
carddav_address_book: "card"
personal_mail_pass_command: "pass personal_mail"
freshrss_pass_command: "pass freshrss"
vdirsyncer_calendar_pass_command: "\"pass\", \"vdirsyncer_calendar\""
vdirsyncer_radicale_pass_command: "\"pass\", \"vdirsyncer_radicale\""
