$ANSIBLE_VAULT;1.1;AES256
38333865346239386336613933363464383838623830323736616633656365633166643962663035
3337656364666336656161653765393035613332643535380a613434613461623036623033313232
63623430633634623034316563303164383839323531353363646636626666626662343839623930
3637383439353230630a316433323739633537303835633061376632656331633366383439343564
35323132373335623731636338366635303736356165366636323566353165643263363838303636
33306637346639363336356637353938663061393866306131316132333466386335383162323063
61346164393566653363653636653437643263306138666135396633613863336332346561656366
62663934323364393133633332353137616264393135366130363566393036316235623666343937
65313063343562333838373438643134633230313133313265333866353635653361363361633365
32626230336564306638616330336666373439623732313065333230343931306566323238613538
63623330623036616363666437316534356233623962643539396636623238313730303231663966
61666438346634323064373835336134636439353637316163313938636337323236343064663539
35303065646130613935353264336136636232653264663337323266393035383235363630303166
34616166326534366334623635653664313264393431316534376461643034343033313730653539
33343534363034343861346561363830373666383166613435393363306534313865373136356239
64346164326333633936343839313936376538376137363365343339363439333866643437366236
62386337313366353662393065373635636566363963386239393632383935326263633737636563
62303635643634316234333763306439333033343638313062663766626265396639313131333431
35376363326439373836653962613866303038636430393131336134633535656461636337663535
65643732646331376230
