$ANSIBLE_VAULT;1.1;AES256
61643830653438633135363932366237646131353265383833393830353166636666383134306466
6630616136383731626565326339366133373565383064390a376233613932303936366232393666
35663130303735383731373866313238396230366536383465333938323935653233636330303330
3438396264616337650a383035663065323661303564326162633137646533646363646638633739
37323234343062373835336237306165626632646238303262373564336436396438303064366339
33643335636163643833333836666239386437643539653231333532333935303131363539383534
35343335346136363739336134613133353832653332353564616561646338323736313162303936
65323233623139616134616130353632616361323935303135363763656564366566393034393837
37656261376538336338393566346338343038323635643563353364643365303266366363383866
34333736626566326165303837653265343631663462353735643066656163613865616564383266
63313431663830633331353531663834303233303661306239633839373963313861323230643935
66663031633764346466376339386431336463306135326164366163373936616631343637306165
62343334383061333631373331323835366563316562313831393536333038653639316537626632
37303263346539303365663663623138353430346532616632633064373439666536343939356533
65366635633665633262343662366166313263306564396630643139366663383065356463396434
33613961323238333732393766623836316662633135633536356631313036626261306565313832
37386636313065636233343666396365383832346133623264316138623039663839333338626535
39333366363263373036393334616364616634343264653865646164336631613164613338663831
34343966386464353739303230393236643261333831356234366436313564313931316335323639
30323964313936623036356637303534323332623063373637653736353163353063363936633663
31633932613337623431353764393266363231306465346530613336633663386136
