---
- name: Reload systemd for nt_file_server
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: true
- name: Restart nt_file_server
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ enabled_services }}"
