---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/{{ item }}"
    state: directory
  loop:
    - samba/data
    - samba/config
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: samba
    image: docker.io/crazymax/samba:{{ samba_version }}
    state: quadlet
    quadlet_filename: samba-container
    network: host
    volumes:
      - "{{ podman_data_dir }}/samba/data:/srv:rw,z"
      # I know this seems wrong but the config file lives here
      - "{{ podman_data_dir }}/samba/config:/data:rw,z"
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      SAMBA_LOG_LEVEL: 0
      # Only allow tailscale ips
      SAMBA_HOSTS_ALLOW: 100.64.0.0/10
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for samba
    - Restart samba
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/samba.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
