---
- name: Write configuration
  ansible.builtin.include_tasks: configure.yml
  when: ansible_facts['os_family'] == 'RedHat'
- name: Install packages
  ansible.builtin.import_tasks: common/tasks/install_packages.yml
- name: Install brew formulae
  ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
