$ANSIBLE_VAULT;1.1;AES256
38656430363838313365373534623139613665323639616366386661323036633035303836383330
6564623030346466386636636636316161633238636234380a656334643934383537303763353439
64646231376136336330373362626131373761323934306236353831646461383034333366353432
3237313766643861640a623039333039393130323463346161373465316538326131366533666366
32326631303931356538363363653565343966393532393633646564303338613961393136646266
63633033613661643937623562613964666561313466303832613735396435663437633439656261
38623833353233326334636331333039653434373932326661343136653433636231343263653361
39663564363331313161386632323437366165636362666138623861613039306265396536646330
65383532666635643965333861343538363631666562346561633938373832386534626534343966
61333166336236613831363665663231623864346637343965336164663035326632336135363266
30323637663234353938353136356532393738383231313831343739626432326161326533393931
39343732323433333035356334373161623230326231386664643862373166653863336564336536
39386532383562323234396334613537326435636266396439303664623266663237653565663861
62343065323566336433646266656462663433653533636265366631366433373763666130656437
31613834336236323133616566623036376534333664356634613430643033653035323734623638
61396665306663623836666362633665306537373365326462333161653231326563353836396232
35343834313636663366373336636434373332653336636334356530643738393362626632303231
62303033346339366333353361393538303638666262303563346632666261666465653731313066
30646131363937353537336166333736626639346464303439303831333763323039323332313464
65336664373938383766303739373930376431303864396535333238303430313637323632356535
31386365333134653234633564623931666235373235616233353531313337353566
