---
- name: Create config directory
  ansible.builtin.file:
    group: "{{ group }}"
    mode: "0755"
    owner: "{{ username }}"
    path: "~/.config/ranger"
    state: directory
- name: Copy ranger rc.conf
  ansible.builtin.copy:
    src: rc.conf
    dest: ~/.config/ranger/rc.conf
    group: "{{ group }}"
    mode: "0644"
    owner: "{{ username }}"
