---
# This is a weird exception, but Oracle Linux ships without the necessary modules for hardware acceleration by default
- name: Install uek desktop kernel modules on Oracle Linux for hardware acceleration
  become: true
  ansible.builtin.dnf:
    name: kernel-uek-modules-desktop
    state: present
  when: ansible_facts["distribution"] == "OracleLinux"
- name: Allow Emby to local network
  become: true
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ emby_port }}"
    comment: Emby
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/{{ item }}"
    state: directory
  loop:
    - emby/config
    - emby/data
    - emby/recordings
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: emby
    image: lscr.io/linuxserver/emby:{{ emby_version }}
    state: quadlet
    quadlet_filename: emby-container
    device:
      - /dev/dri:/dev/dri
    network: host
    volumes:
      - "{{ podman_data_dir }}/emby/config:/config:rw,z"
      - "{{ podman_data_dir }}/emby/data:/mnt:ro,z"
      - "{{ podman_data_dir }}/emby/recordings:/recordings:rw,z"
      # For pinchflat downloads, needs rw to delete
      - "{{ podman_data_dir }}/pinchflat/data:/pinchflat:rw,z"
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for emby
    - Restart emby
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/emby.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/emby.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for emby
    - Restart emby
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
