---
- name: Reload systemd for adventurelog
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: true
- name: Restart adventurelog
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ enabled_services }}"
