---
- name: Create newsboat config directory
  ansible.builtin.file:
    group: "{{ group }}"
    mode: "0755"
    owner: "{{ username }}"
    path: "~/.config/newsboat"
    state: directory
- name: Configure newsboat settings
  ansible.builtin.template:
    src: config.j2
    dest: "~/.config/newsboat/config"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0644"
- name: Copy dummy newsboat url file
  ansible.builtin.copy:
    src: urls
    dest: ~/.config/newsboat/urls
    group: "{{ group }}"
    mode: "0644"
    owner: "{{ username }}"
