---
# this is the same version in debian 13
packages:
  - git
brew_formulae:
  - git
  - gitlint
full_name: "{{ username }}"
email: "{{ username }}@localhost"
pip_packages:
  - name: gitlint
    install: gitlint==0.19.1
