---
first_name: "Alex"
username: alex
group: alex
full_name: "Alex Taylor"
email: "ataylor@posteo.us"
podman_data_dir: "/var/opt"
ssh_key_name: "id_ed25519"
tailscale_authkey: "dummy"
caddy_root_domain_block:
default_quadlet_options:
  - AutoUpdate=registry
  - Pull=missing
  - |
    [Unit]
    After=network-online.target nss-lookup.target

    [Service]
    Restart=always

    [Install]
    WantedBy=default.target
