$ANSIBLE_VAULT;1.1;AES256
63343232653864363736373331646361653663323233303130356465396364653662653530636233
6364333239636631373333376333303934613437396138650a306538396432303632366363333733
63663162383664656666363733343166393366393039636466353331323539373265373763343434
3364656462376332380a663261346433343839623336326438636265613536613764613766376635
66396438366561363334383065616138393963626434313561396438363939336439643434303434
61653961353163353032613161616566626134636638393965393635336331326636666635316465
32386231366132643566613036313662646466663366653330626533613338626330363166613330
34386233376266653730623464646437363435376635363432396131316633636561663438626663
64346535623838623336306439326432333666643037323834353837376665303862653934393963
31643036356661353635643233393739386538393564633737666335623837613338386630383734
38313062316465326566626230353763663134333030633635656664616136343962363365653739
37646665373464343330323664303165666562626265366332336433313863653637656231313161
30346436646430643734656464363839623131323235343631313238316330653836
