$ANSIBLE_VAULT;1.1;AES256
39366265383066356264313431326161383562356230383765633237643833653366613162306338
6138306532376135396462323937643566643430653134650a396332363737633966333764353131
34656465383963393765343066386433303033343936396265633838313035323963383763616435
3761643836303038390a363937626465336237333338663536336364363663343937393630353935
66303865326135326131623238346439346664333266343665633365623638333262666430303837
36636463613835636539633364356333663139653332383064396330336634326237323539393862
61313535386564346533346138666635666662383066643237616130326232666661383261636434
36323939303162396636666434386261363064386662306333626531346631303362316265313632
30326565613030643630653461366137666666626133646430393235346234393638316530343661
30303962383461653062356237373333336465363537666466306164366534616338386361313836
36396339373437393463633061666135616130643332326163666530343934343631363730333136
64316632333962316466
