---
- name: Install formulae
  when: ansible_facts['os_family'] == 'Darwin'
  ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
  vars:
    brew_formulae:
      - mas
- name: Uninstall apps using mas
  when: ansible_facts['os_family'] == 'Darwin'
  become: true
  community.general.mas:
    id: "{{ item }}"
    state: absent
  loop: "{{ mas_apps }}"
