$ANSIBLE_VAULT;1.1;AES256
37656535393465383636323533303032303030343632353963616332313531643963623337666438
6130313865366232303462363936383363653338626334640a343865616330636234396566303036
65356632386339386136343165333737383364643731376637656637373366633164393062333033
3064376436363232330a663632343464373736346332353139616331333363663238373764343534
66353535613733646364353739623265323162383562316438626531373330613830616561653834
6566656331363433366436326531316436393037383662323833
