---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/{{ item }}"
    state: directory
  loop:
    - immich-server
    - immich-machine-learning
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    # The container enforces this mode and gid
    mode: "0700"
    owner: 999
    path: "{{ podman_data_dir }}/immich-postgres"
    state: directory
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    # The container enforces this gid
    owner: 999
    path: "{{ podman_data_dir }}/immich-redis"
    state: directory
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: immich-redis
    image: docker.io/valkey/valkey:{{ immich_redis_version }}
    state: quadlet
    quadlet_filename: immich-redis-container
    network: "{{ default_podman_interface }}"
    volumes:
      - "{{ podman_data_dir }}/immich-redis:/data:rw,z"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for immich
    - Restart immich
- name: Create a Quadlet file
  become: true
  no_log: true
  containers.podman.podman_container:
    name: immich-postgres
    image: ghcr.io/immich-app/postgres:{{ immich_postgres_version }}
    state: quadlet
    quadlet_filename: immich-postgres-container
    network: "{{ default_podman_interface }}"
    volumes:
      - "{{ podman_data_dir }}/immich-postgres:/var/lib/postgresql/data:rw,z"
    env:
      POSTGRES_PASSWORD: "{{ immich_database_password }}"
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: --data-checksums
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for immich
    - Restart immich
- name: Create a Quadlet file
  become: true
  no_log: true
  containers.podman.podman_container:
    name: immich-server
    image: ghcr.io/immich-app/immich-server:{{ immich_server_version }}
    state: quadlet
    quadlet_filename: immich-server-container
    ports:
      - 127.0.0.1:{{ immich_port }}:2283
    network: "{{ default_podman_interface }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro,z
      - "{{ podman_data_dir }}/immich-server:/usr/src/app/upload:rw,z"
    env:
      TZ: America/New_York
      DB_PASSWORD: "{{ immich_database_password }}"
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich-postgres
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for immich
    - Restart immich
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:{{ immich_server_version }}
    state: quadlet
    quadlet_filename: immich-machine-learning-container
    network: "{{ default_podman_interface }}"
    volumes:
      - "{{ podman_data_dir }}/immich-machine-learning:/cache:rw,z"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for immich
    - Restart immich
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/immich.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/immich.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for immich
    - Restart immich
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
