---
# this is the same version in debian 13
borgmatic_version: 1.9.14
packages:
  - borgbackup
  - lz4
  - sqlite
pip_packages:
  - borgmatic=={{ borgmatic_version }}
brew_formulae:
  - borgbackup
  - lz4
brew_casks:
  - vorta
