---
# this is the same version in debian 13
packages:
  - borgbackup
  - lz4
  - sqlite
pip_packages:
  - name: borgmatic
    install: borgmatic==1.9.14
brew_formulae:
  - borgbackup
  - lz4
brew_casks:
  - vorta
