---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/{{ item }}"
    state: directory
  loop:
    - pinchflat/config
    - pinchflat/data
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: pinchflat
    image: ghcr.io/kieraneglin/pinchflat:{{ pinchflat_version }}
    state: quadlet
    quadlet_filename: pinchflat-container
    network: "{{ default_podman_interface }}"
    ports:
      - 127.0.0.1:{{ pinchflat_port }}:8945
    user: 1000:1000
    volumes:
      - "{{ podman_data_dir }}/pinchflat/config:/config:rw,z"
      - "{{ podman_data_dir }}/pinchflat/data:/downloads:rw,z"
    env:
      TZ: America/New_York
      YT_DLP_WORKER_CONCURRENCY: 1
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for pinchflat
    - Restart pinchflat
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/pinchflat.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/pinchflat.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for pinchflat
    - Restart pinchflat
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
