---
- name: Reload systemd for paperless
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: true
- name: Restart paperless
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ enabled_services }}"
