---
- name: Create config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/mealie"
    state: directory
- name: Create a Quadlet file
  become: true
  no_log: true
  containers.podman.podman_container:
    name: mealie
    image: ghcr.io/mealie-recipes/mealie:{{ mealie_version }}
    state: quadlet
    quadlet_filename: mealie-container
    network: "{{ default_podman_interface }}"
    env:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      BASE_URL: https://{{ subdomain_name }}.{{ domain_name }}
      OPENAI_API_KEY: "{{ mealie_openai_key }}"
      API_DOCS: "false"
      OPENAI_SEND_DATABASE_DATA: "false"
    ports:
      - 127.0.0.1:{{ mealie_port }}:9000
    volumes:
      - "{{ podman_data_dir }}/mealie:/app/data:rw,z"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for mealie
    - Restart mealie
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/mealie.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for mealie
    - Restart mealie
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/mealie.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
