---
- name: Install packages
  ansible.builtin.import_tasks: common/tasks/install_packages.yml
- name: Add brew tap
  ansible.builtin.import_tasks: common/tasks/install_brew_tap.yml
- name: Install brew formulae
  ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
- name: Install brew casks
  ansible.builtin.import_tasks: common/tasks/install_brew_casks.yml
- name: Write configuration
  ansible.builtin.include_tasks: configure.yml
