---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/{{ item }}"
    state: directory
  loop:
    - wishlist/images
    - wishlist/data
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: wishlist
    image: ghcr.io/cmintey/wishlist:{{ wishlist_version }}
    state: quadlet
    quadlet_filename: wishlist-container
    network: "{{ default_podman_interface }}"
    env:
      ORIGIN: https://wishlist.{{ domain_name }}
      TOKEN_TIME: 72
    ports:
      - 127.0.0.1:{{ wishlist_port }}:3280
    volumes:
      - "{{ podman_data_dir }}/wishlist/images:/usr/src/app/uploads:rw"
      - "{{ podman_data_dir }}/wishlist/data:/usr/src/app/data:rw"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for wishlist
    - Restart wishlist
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/wishlist.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for wishlist
    - Restart wishlist
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/wishlist.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
