---
- name: Create caddy config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: /etc/caddy
    state: directory
- name: Create caddy sites-enabled directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: /etc/caddy/sites-enabled
    state: directory
- name: Create caddy directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/caddy"
    state: directory
- name: Create caddy config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/caddy/config"
    state: directory
- name: Create caddy data directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/caddy/data"
    state: directory
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify: Restart caddy
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: caddy
    image: ghcr.io/caddybuilds/caddy-cloudflare:{{ caddy_version }}
    state: quadlet
    quadlet_filename: caddy-container
    user: 1000:1000
    network: host
    dns:
      - "{{ local_gateway }}"
    volumes:
      - /etc/caddy:/etc/caddy:ro
      - "{{ podman_data_dir }}/caddy/config:/config:rw"
      - "{{ podman_data_dir }}/caddy/data:/data:rw"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for caddy
    - Restart caddy
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
