$ANSIBLE_VAULT;1.1;AES256
34336137373337383066633266336338353063393633393662313165653831363665653338303837
6534613838326137386639333761353765666638363835640a636137396638643334623536663638
36313864666234623639303833623964623035643738313463386239643939623037633363383933
3661313333626462620a643435613934316433613637636333626133323032323939663439396238
34396530663237313936313265386262346433333263663837346663623637376362
