---
vdirsyncer_directory: "~/.local/share/vdirsyncer"
todoman_version: 4.6.0
packages:
  - vdirsyncer
  - khal
  - khard
brew_formulae:
  - vdirsyncer
  - khal
  - khard
  - todoman
pip_packages:
  - todoman=={{ todoman_version }}
