$ANSIBLE_VAULT;1.1;AES256
35376664616538346337343732333934383333383237346232356336323833646538393461663861
6135666331373630333335353035633937303436363634330a663732366337393135353863323065
63653432646338653961633261653439663833633061333063336630666431383735613264373038
3330323263356363640a326430383562383962653639383039353465303266633331346232363735
32333663353538666638353232333731383835333435336438666634383530616630313139633962
33316233353639353137373239303934353039653933646634363832396362626661306665383237
30353434653761396630303330316634323233313230373831376332613039666336333732363863
63643665343032373738653165383266613432643766653638616563313562313833666331613932
36323734313037316530666133666638336261366164646632326237343439633731
