---
- name: Create config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/open-webui"
    state: directory
- name: Create a Quadlet file
  become: true
  no_log: true
  containers.podman.podman_container:
    name: open-webui
    image: ghcr.io/open-webui/open-webui:{{ open_webui_version }}
    state: quadlet
    env:
      WEBUI_URL: https://{{ subdomain_name }}.{{ domain_name }}
      WEBUI_SECRET_KEY: "{{ open_webui_secret_key }}"
      ENABLE_SIGNUP: false
      ENABLE_OLLAMA_API: false
      ENABLE_OPENAI_API: true
      OPENAI_API_KEY: "{{ open_webui_openai_key }}"
      ENABLE_FOLLOW_UP_GENERATION: false
    quadlet_filename: open-webui-container
    network: "{{ default_podman_interface }}"
    ports:
      - 127.0.0.1:{{ open_webui_port }}:8080
    volumes:
      - "{{ podman_data_dir }}/open-webui:/app/backend/data:rw,z"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for open-webui
    - Restart open-webui
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/open_webui.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for open-webui
    - Restart open-webui
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/open_webui.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
