$ANSIBLE_VAULT;1.1;AES256
36373938393565313132663030353961303762363933623337303835306230326135323837636237
3363373263623363303764643136393136623630363030640a316463613435356330646435313461
34353664306138653639346231643637393236373432623233343162333338356430333766623534
6361323466373134320a616464366663663661393534653837383830316330323838393632373435
66393637353636623939313065313933323432663563616634623539326562306231646631333063
62303766363936663563623362363962323235633834326235336437376135383931313535336336
39383965393661653064323231383538336136303262363262396164663030636137383239616131
61316230643462626330613930643331616364363464393831343966363264616533373632613265
34346338386663666139316165623333626633343530646131666564393061626632313434656662
34363637383061376430313836396361616466346563306231326136373033633166646438353335
30323936653965343163303261343833346365653436353865346462633137633338353462343866
37336563643932326436336362303134626533373934393833343937333439353566613131376535
66653932373266663239666233346361353237636636323530366363373737613437303163333731
38373435386531653463353534333339303137623062356162616361663737333262643632646338
37313934376539353262343038336236613436356462653466323663666539336237663565343261
30646638626365633233373636333633353339333930326163613464643932313063386363383565
32333531323861323233333931633062666233373333613839366533633935646665633361336334
30646236336339613461333962313539366265323933333036366438653464333437353533383563
38316263663134313537346261643661373035616265663235386538623633313035363832646433
30613933366562626432303737653965353161343935363561366336643536303735353964383738
6466
