---
- name: Write configuration
  ansible.builtin.include_tasks: configure.yml
- name: Install packages
  ansible.builtin.import_tasks: common/tasks/install_packages.yml
- name: Install brew casks
  ansible.builtin.import_tasks: common/tasks/install_brew_casks.yml
