---
- name: Sync all clients
  hosts: localhost
  tasks:
    - name: Discover CalDAV & CardDAV collections
      ansible.builtin.command: "bash -c 'yes | vdirsyncer discover'"
    - name: Sync CalDAV & CardDAV
      ansible.builtin.command: vdirsyncer sync
    - name: Sync CalDAV & CardDAV metadata
      ansible.builtin.command: vdirsyncer metasync
