---
- name: Create data directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/samba"
    state: directory
- name: Generate smb.conf
  become: true
  ansible.builtin.template:
    src: smb.conf.j2
    dest: "{{ podman_data_dir }}/samba/smb.conf"
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for nt_file_server
    - Restart nt_file_server
- name: Generate users.conf
  become: true
  no_log: true
  ansible.builtin.template:
    src: users.conf.j2
    dest: "{{ podman_data_dir }}/samba/users.conf"
    group: 1000
    mode: "0600"
    owner: 1000
  notify:
    - Reload systemd for nt_file_server
    - Restart nt_file_server
- name: Allow SMB
  become: true
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "445"
    comment: Samba
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: samba
    image: docker.io/dockurr/samba:{{ samba_version }}
    state: quadlet
    quadlet_filename: samba-container
    network: host
    volumes:
      - "{{ podman_data_dir }}/paperless-server/consume:{{ podman_data_dir }}/paperless-server/consume:rw,z"
      - "{{ podman_data_dir }}/samba/smb.conf:/etc/samba/smb.conf:ro,z"
      - "{{ podman_data_dir }}/samba/users.conf:/etc/samba/users.conf:ro,z"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for nt_file_server
    - Restart nt_file_server
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/samba.yaml
    group: root
    mode: "0600"
    owner: root
    src: borgmatic.yaml.j2
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
